- native.js
- src/components/Button/native/Button.js
- src/components/Spacer/native/Spacer.js
- src/components/Spacer/native/index.js
- src/components/Text/Text.js
- src/components/Text/native/Text.js
- src/theme/theme.js
- storybook/native/stories.js
- Configurable button component added for react native projects
- Changing the structure of native.js so that project can be imported as a dependency smoothly
> Button component for react native

- src/components/Select/Select.js
Select component doesnt show the label of the selected option (in single mode), instead it shows the value.
> fix Issue #7 - Select doesnt show correct label

- src/components/Notification/Notification.js
- src/components/Notification/Notification.story.js
And added a story for Notification "types".
> Updated <Notification/> type prop validator

- src/components/Button/Button.js
- src/components/Form/Form.story.js
Disables Button: On button type submit ,when field values have validation errors.
> Disable Button when Form has validation errors

- .github/ISSUE_TEMPLATE.md
> chore(issue_template)

- src/Position/amp/index.js
- src/Position/web/Position.js
- src/Position/web/index.js
> feat(Position/web): add Position component

- src/Checkbox/web/Checkbox.js
- src/Form/makeStories.js
- src/Form/web/Form.story.js
- src/RadioButton/web/RadioButton.js
- src/Select/web/Select.js
- src/TextInput/web/TextInput.js
use getIn on formik.values as field name could be a path instead of an atomic field name
> Use getIn from formik to access form values by field name

- src/Card/makeStories.js
- src/Card/web/Card.js
I have added borderStyle and shape property in card. shape can have bluntEdged ,sharpEdged, capsular, circular like a button.
> feat(Card): add borderStyle and shape property in card component

- src/Flex/native/Flex.js
- src/Position/native/Position.js
- src/Position/native/index.js
- src/Size/native/Size.js
- src/Space/native/Space.js
- src/Text/makeStories.js
- src/Text/native/Text.js
- src/Text/native/Text.story.js
- src/View/native/View.js
- storybook/native/config.js
What this PR brings:
1. Fixes in Enhancers on native (Conformance to new API guidelines)
2. Fixes over Text component
3. Stories are working on native now, removing the blocker we had on native contributions
> native/new-api: 

- src/Gallery/web/Gallery.js
> fix(gallery): vertical scrolling is slow and stuck in ios safari

- src/Tag/makeStories.js
- src/Tag/native/Tag.js
- src/Tag/web/Tag.js
All Tag should have medium font weight & small should have ALL CAPS text
> fix(Tag): All Tag should have medium font weight & small should have ALL CAPS text

- src/Select/web/Select.js
> fix(Select): Select Placeholder color - greyLight

- src/Select/web/Label.js
> fix(Select): Select Label Colour - greyDark

- src/Select/web/Select.js
> fix(Select): Error message font-size should be 12px

- src/TextArea/native/TextArea.js
- src/TextArea/web/Label.js
> fix(TextInputArea): Text Input Area Colour - greyDark

- src/TextInput/native/TextInput.js
- src/TextInput/web/Label.js
> fix(TextInput): Text Input Label Colour - greyDark

- src/TextArea/web/TextArea.js
> fix(TextArea): Error message font-size should be 12px TextArea

- src/TextInput/web/TextInput.js
> fix(TextInput): Error message font-size should be 12px TextInput

- src/Button/web/Button.js
> fix(Button): Secondary button should have white fill

- src/Checkbox/web/Label.js
- src/RadioButton/web/Label.js
> fix(checkbox and radiobutton): All Inputs Label Colour - greyDark

- src/Checkbox/web/Checkbox.js
- src/RadioButton/web/RadioButton.js
> fix(checkbox and radiobutton): All inputs Error message font-size should be 12px

- src/Tag/web/Tag.js
> fix(Tag): Tag font-size

- src/DatePickerInput/web/DatePickerInput.js
- src/DateRangePickerInput/web/DateRangePickerInput.js
> fix(DateRangePickerInput): date-range-picker-input error message reset issue(#180)

- package-lock.json
- package.json
Hello! Since you have a Storybook I figured you might want to have some visual regression testing against it. I am currently an apprentice that is helping Applitools get up and running on different open source projects so that projects can enjoy the benefit of visual testing.
If you're not familiar with automated visual regression testing there's a pretty good summary [in the Storybook docs](https://github.com/storybooks/storybook/blob/master/docs/src/pages/testing/automated-visual-testing/index.md). Visual regression involves comparing the pixels visually like a human would, ideally ignoring differences that a human couldn't perceive e.g. 1 pixel changes, differences in how browsers render images, drop shadows, etc. to avoid false positives; but you can still do a strict 1:1 pixel match …
> Add Visual Testing with Applitools
